import type { Question, Difficulty } from './types';

const generateQuestions = (): Record<Difficulty, Question[]> => {
  const easy: Question[] = [
    // 50 Easy Questions from the provided paper
    {
      questionText: "What does HARS stand for?",
      options: ["Hamilton Anxiety Rating Scale", "Holistic Anxiety Reduction System", "Human Agitation Response Scale", "Health and Relaxation Score"],
      correctAnswerIndex: 0,
      reference: "Page 1, Abstract & Page 3, Section 2.2",
      difficulty: 'easy',
    },
    {
      questionText: "What is the primary technique investigated in the study?",
      options: ["Deep Breathing", "Mindful Meditation", "Butterfly Hug", "Yoga Therapy"],
      correctAnswerIndex: 2,
      reference: "Page 1, Title and Abstract",
      difficulty: 'easy',
    },
    {
      questionText: "How many participants were involved in this case study?",
      options: ["One", "Three", "Ten", "Twenty"],
      correctAnswerIndex: 1,
      reference: "Page 1, Abstract & Page 4, Section 3",
      difficulty: 'easy',
    },
    {
      questionText: "What was the average point reduction on the HARS scale for the participants?",
      options: ["10.5 points", "14.0 points", "17.3 points", "25.0 points"],
      correctAnswerIndex: 2,
      reference: "Page 1, Abstract & Page 5, Paragraph 1",
      difficulty: 'easy',
    },
    {
      questionText: "The study focused on students from which grade level?",
      options: ["Ninth-grade", "Tenth-grade", "Eleventh-grade", "Twelfth-grade"],
      correctAnswerIndex: 1,
      reference: "Page 1, Abstract",
      difficulty: 'easy',
    },
    {
      questionText: "The Butterfly Hug technique is a form of bilateral stimulation developed within which therapy framework?",
      options: ["Cognitive Behavioral Therapy (CBT)", "Psychoanalytic Therapy", "Dialectical Behavior Therapy (DBT)", "Eye Movement Desensitization and Reprocessing (EMDR)"],
      correctAnswerIndex: 3,
      reference: "Page 2, Paragraph 4",
      difficulty: 'easy',
    },
    {
      questionText: "According to the HARS classification in the paper, what score range indicates 'Moderate anxiety'?",
      options: ["14-20", "21-27", "28-41", "≥42"],
      correctAnswerIndex: 1,
      reference: "Page 3, Section 2.2",
      difficulty: 'easy',
    },
    {
      questionText: "What is the HARS score for someone with 'No anxiety'?",
      options: ["0-13", "14-20", "21-27", "Cannot be determined"],
      correctAnswerIndex: 0,
      reference: "Page 3, Section 2.2",
      difficulty: 'easy',
    },
    {
      questionText: "The Butterfly Hug involves crossing the arms over the chest and alternately tapping what?",
      options: ["The knees", "The opposite arms/shoulders", "The chest directly", "The legs"],
      correctAnswerIndex: 1,
      reference: "Page 3, Section 2.3",
      difficulty: 'easy',
    },
    {
      questionText: "After the intervention, participants reported feeling calmer and relieved as their ______ faded.",
      options: ["physical pain", "positive memories", "negative thoughts", "hunger"],
      correctAnswerIndex: 2,
      reference: "Page 5, Paragraph 3",
      difficulty: 'easy',
    },
    {
      questionText: "What type of school was the setting for this study?",
      options: ["Public Day School", "Charter School", "Boarding School", "Online School"],
      correctAnswerIndex: 2,
      reference: "Page 1, Abstract",
      difficulty: 'easy',
    },
    {
      questionText: "What was the research design used in this study?",
      options: ["Experimental Design", "Correlational Study", "Descriptive Case Study", "Longitudinal Study"],
      correctAnswerIndex: 2,
      reference: "Page 4, Section 3",
      difficulty: 'easy',
    },
    {
      questionText: "One participant mentioned that the exercise felt like what?",
      options: ["'Floating on a cloud'", "'Being hugged by my mother'", "'Listening to music'", "'A good workout'"],
      correctAnswerIndex: 1,
      reference: "Page 5, Paragraph 3",
      difficulty: 'easy',
    },
    {
      questionText: "According to the World Health Organization (2022), what fraction of adolescents globally suffers from a mental health disorder?",
      options: ["One in three", "One in five", "One in seven", "One in ten"],
      correctAnswerIndex: 2,
      reference: "Page 2, Paragraph 2",
      difficulty: 'easy',
    },
    {
      questionText: "What were the two types of anxiety that the HARS assesses?",
      options: ["Social and performance anxiety", "Acute and chronic anxiety", "Psychic and somatic anxiety", "Generalized and specific anxiety"],
      correctAnswerIndex: 2,
      reference: "Page 3, Section 2.2",
      difficulty: 'easy',
    },
    {
      questionText: "The study states that the Butterfly Hug's simplicity makes it suitable for adolescents facing homesickness, academic pressure, and what else?",
      options: ["Social adjustment", "Financial difficulties", "Family conflicts", "Sports injuries"],
      correctAnswerIndex: 0,
      reference: "Page 5, Paragraph 4",
      difficulty: 'easy',
    },
    {
      questionText: "How were participants selected for the study?",
      options: ["Random sampling", "Convenience sampling", "Purposive sampling", "Snowball sampling"],
      correctAnswerIndex: 2,
      reference: "Page 4, Section 3",
      difficulty: 'easy',
    },
    {
      questionText: "In Table 4.1, what was Participant 2's anxiety level *before* the intervention?",
      options: ["Low", "Moderate", "High", "Very High"],
      correctAnswerIndex: 3,
      reference: "Page 4, Table 4.1",
      difficulty: 'easy',
    },
    {
      questionText: "In Table 4.1, what was the anxiety level for all three participants *after* the intervention?",
      options: ["Low", "Moderate", "High", "It varied"],
      correctAnswerIndex: 0,
      reference: "Page 4, Table 4.1",
      difficulty: 'easy',
    },
    {
      questionText: "What is one of the key benefits of the Butterfly Hug mentioned in the conclusion?",
      options: ["It increases physical strength", "It helps manage negative thoughts and emotions", "It improves memory retention", "It requires a trained therapist"],
      correctAnswerIndex: 1,
      reference: "Page 5, Conclusion",
      difficulty: 'easy',
    },
    {
      questionText: "Which of the following was NOT a data collection technique used in the study?",
      options: ["Hamilton Anxiety Rating Scale (HARS)", "Classroom observations", "Written standardized tests", "Semi-structured interviews"],
      correctAnswerIndex: 2,
      reference: "Page 4, Section 3",
      difficulty: 'easy',
    },
    {
      questionText: "The author's email provided in the paper is at what domain?",
      options: ["yahoo.com", "nurulfikri.ac.id", "gmail.com", "outlook.com"],
      correctAnswerIndex: 2,
      reference: "Page 1, Author Information",
      difficulty: 'easy',
    },
    {
      questionText: "The affirmation stage of the Butterfly Hug process helped participants develop stronger self-acceptance and what else?",
      options: ["Public speaking skills", "Self-appreciation", "Athletic ability", "Mathematical skills"],
      correctAnswerIndex: 1,
      reference: "Page 1, Abstract",
      difficulty: 'easy',
    },
    {
      questionText: "The 'Butterfly Hug' is described as a self-soothing and _______ stimulation technique.",
      options: ["unilateral", "bilateral", "cognitive", "emotional"],
      correctAnswerIndex: 1,
      reference: "Page 3, Section 2.3",
      difficulty: 'easy',
    },
    {
      questionText: "According to Leitch (2020), the Butterfly Hug promotes self-soothing, emotional regulation, and a sense of what?",
      options: ["Detachment", "Euphoria", "Grounding", "Superiority"],
      correctAnswerIndex: 2,
      reference: "Page 2, Paragraph 4",
      difficulty: 'easy',
    },
    {
        questionText: "Who developed the Hamilton Anxiety Rating Scale (HARS)?",
        options: ["Leitch (2020)", "Hamilton (1959)", "Yin (2023)", "Braun & Clarke (2021)"],
        correctAnswerIndex: 1,
        reference: "Page 3, Section 2.2",
        difficulty: 'easy',
    },
    {
        questionText: "What visible changes were observed in participants after the intervention?",
        options: ["They became more withdrawn", "They showed calmer behavior and better focus", "Their grades immediately improved", "They slept more in class"],
        correctAnswerIndex: 1,
        reference: "Page 5, Paragraph 2",
        difficulty: 'easy',
    },
    {
        questionText: "What is the title of the research paper?",
        options: ["Anxiety in Boarding Schools", "The Power of the Butterfly Hug", "A Study on Adolescent Mental Health", "Investigating Anxiety Reduction Through Butterfly Hug Technique..."],
        correctAnswerIndex: 3,
        reference: "Page 1, Title",
        difficulty: 'easy',
    },
    {
        questionText: "The HARS scale rates each item on a scale from 0 (none) to what number (severe)?",
        options: ["3", "4", "5", "10"],
        correctAnswerIndex: 1,
        reference: "Page 3, Section 2.2",
        difficulty: 'easy',
    },
    {
        questionText: "Prolonged anxiety in students can negatively affect concentration, motivation, and what else?",
        options: ["Physical height", "Eye color", "Overall academic performance", "Favorite subjects"],
        correctAnswerIndex: 2,
        reference: "Page 2, Paragraph 3",
        difficulty: 'easy',
    },
    {
        questionText: "The study's conclusion suggests the Butterfly Hug is a simple and _____ method for reducing anxiety.",
        options: ["expensive", "complicated", "practical", "time-consuming"],
        correctAnswerIndex: 2,
        reference: "Page 5, Conclusion",
        difficulty: 'easy',
    },
    {
        questionText: "The paper mentions that anxiety is one of the most _____ mental health issues.",
        options: ["rare", "prevalent", "misunderstood", "newly discovered"],
        correctAnswerIndex: 1,
        reference: "Page 2, Paragraph 2",
        difficulty: 'easy',
    },
    {
        questionText: "Data were analyzed using both quantitative and _____ approaches.",
        options: ["historical", "qualitative", "philosophical", "hypothetical"],
        correctAnswerIndex: 1,
        reference: "Page 4, Section 3",
        difficulty: 'easy',
    },
    {
        questionText: "Participant 1's HARS score decreased from 23 to what number?",
        options: ["5", "9", "14", "19"],
        correctAnswerIndex: 1,
        reference: "Page 4, Table 4.1",
        difficulty: 'easy',
    },
    {
        questionText: "Participant 3 experienced what level of reduction according to the table's description?",
        options: ["Significant reduction", "Decreased anxiety level", "Moderate reduction", "No change"],
        correctAnswerIndex: 2,
        reference: "Page 4, Table 4.1",
        difficulty: 'easy',
    },
    {
        questionText: "The research procedure included permission, consent, pre-test, intervention, post-test, and what final step?",
        options: ["Publication", "Group discussion", "Final interviews", "A party"],
        correctAnswerIndex: 2,
        reference: "Page 4, Paragraph 4",
        difficulty: 'easy',
    },
    {
        questionText: "The study aimed to investigate the effectiveness of the technique on what population?",
        options: ["Elderly adults", "University students", "Adolescents", "Young children"],
        correctAnswerIndex: 2,
        reference: "Page 1, Abstract",
        difficulty: 'easy',
    },
    {
        questionText: "Ethical standards such as informed consent, confidentiality, and ____ were ensured.",
        options: ["payment", "anonymity", "publicity", "plagiarism"],
        correctAnswerIndex: 1,
        reference: "Page 4, Paragraph 4",
        difficulty: 'easy',
    },
    {
        questionText: "What does NFBS stand for?",
        options: ["National Foundation for Boarding Schools", "New Foundational Behavioral Science", "Nurul Fikri Boarding School", "Notable Factual Boarding School"],
        correctAnswerIndex: 2,
        reference: "Page 2, Paragraph 3",
        difficulty: 'easy',
    },
    {
        questionText: "The introduction states that adolescence is a crucial stage of human development characterized by rapid emotional, physical, and ____ transitions.",
        options: ["financial", "political", "social", "linguistic"],
        correctAnswerIndex: 2,
        reference: "Page 2, Paragraph 2",
        difficulty: 'easy',
    },
    {
        questionText: "According to the abstract, what can symptoms like emotional distress and withdrawal highlight the need for?",
        options: ["More homework", "Stricter rules", "Effective self-regulation techniques", "Longer school holidays"],
        correctAnswerIndex: 2,
        reference: "Page 1, Abstract",
        difficulty: 'easy',
    },
    {
        questionText: "The paper by Risprianto (2022) found that the technique reduced anxiety and emotional tension among Indonesian adolescents experiencing what?",
        options: ["Family conflict", "Academic stress", "Social media pressure", "Financial hardship"],
        correctAnswerIndex: 1,
        reference: "Page 2, Paragraph 5",
        difficulty: 'easy',
    },
    {
        questionText: "What is the third step of the Butterfly Hug technique as described in the paper?",
        options: ["Singing a song", "Standing on one leg", "Focusing on the rhythmic tapping and breathing", "Writing down your thoughts"],
        correctAnswerIndex: 2,
        reference: "Page 3, Section 2.3",
        difficulty: 'easy',
    },
    {
        questionText: "The study's results showed a notable _____ in anxiety across all participants.",
        options: ["increase", "stabilization", "fluctuation", "decrease"],
        correctAnswerIndex: 3,
        reference: "Page 1, Abstract",
        difficulty: 'easy',
    },
    {
        questionText: "One of the keywords listed for the paper is 'Emotional _____'.",
        options: ["Distress", "Intelligence", "Regulation", "Outburst"],
        correctAnswerIndex: 2,
        reference: "Page 1, Keywords",
        difficulty: 'easy',
    },
    {
        questionText: "The paper states that the onset of any anxiety disorder is usually in _____.",
        options: ["childhood", "adulthood", "old age", "adolescence"],
        correctAnswerIndex: 0,
        reference: "Page 2, Section 2.1",
        difficulty: 'easy',
    },
    {
        questionText: "Chronic anxiety in adolescence can contribute to low _____ later in life.",
        options: ["income", "self-esteem", "blood pressure", "height"],
        correctAnswerIndex: 1,
        reference: "Page 2, Paragraph 3",
        difficulty: 'easy',
    },
    {
        questionText: "The conclusion recommends applying this technique to a larger and more _____ sample in future research.",
        options: ["uniform", "wealthy", "diverse", "local"],
        correctAnswerIndex: 2,
        reference: "Page 5, Conclusion",
        difficulty: 'easy',
    },
    {
        questionText: "The study involved only _____ students.",
        options: ["male", "female", "athlete", "international"],
        correctAnswerIndex: 1,
        reference: "Page 1, Abstract",
        difficulty: 'easy',
    },
    {
        questionText: "What was the difference in HARS score for Participant 2?",
        options: ["13", "14", "19", "25"],
        correctAnswerIndex: 3,
        reference: "Page 4, Table 4.1",
        difficulty: 'easy',
    },
  ];

  const medium: Question[] = [
    // 25 Medium Questions from the provided paper
    {
      questionText: "Why was the Butterfly Hug technique considered a 'promising approach' for managing anxiety in the introduction?",
      options: ["It is the only technique that works", "It promotes self-soothing, emotional regulation, and a sense of grounding", "It is recommended by the World Health Organization", "It is a form of physical exercise"],
      correctAnswerIndex: 1,
      reference: "Page 2, Paragraph 4",
      difficulty: 'medium',
    },
    {
      questionText: "The study used a 'descriptive case study design'. What is the main purpose of this type of design according to Yin (2023)?",
      options: ["To test a hypothesis about a large population", "To investigate a phenomenon in its real-life context for holistic understanding", "To prove a cause-and-effect relationship", "To compare the results of multiple different interventions"],
      correctAnswerIndex: 1,
      reference: "Page 4, Section 3",
      difficulty: 'medium',
    },
    {
      questionText: "What is meant by 'data triangulation' as implemented in this study?",
      options: ["Using three different statistical tests", "Collecting data at three different times", "Using three different techniques to collect data for a comprehensive picture", "Interviewing participants from three different schools"],
      correctAnswerIndex: 2,
      reference: "Page 4, Section 3",
      difficulty: 'medium',
    },
    {
      questionText: "The paper contrasts the age-of-onset for anxiety disorders with which other conditions?",
      options: ["Eating disorders and ADHD", "Depressive or substance use disorders", "Personality disorders", "Learning disabilities"],
      correctAnswerIndex: 1,
      reference: "Page 2, Section 2.1",
      difficulty: 'medium',
    },
    {
      questionText: "How does the study explain the mechanism of the Butterfly Hug? It activates relaxation responses and helps _____.",
      options: ["strengthen muscles", "improve memory", "integrate emotions", "increase heart rate"],
      correctAnswerIndex: 2,
      reference: "Page 5, Paragraph 4",
      difficulty: 'medium',
    },
    {
      questionText: "What is the core reason provided in the paper for why boarding school life is a unique stressor for adolescents?",
      options: ["Lack of extracurricular activities", "Poor quality of food and lodging", "The combination of separation from family, academic demands, and peer relationships", "The distance from urban centers and entertainment"],
      correctAnswerIndex: 2,
      reference: "Page 2, Paragraph 3",
      difficulty: 'medium',
    },
    {
      questionText: "The conclusion suggests comparing the Butterfly Hug's effectiveness with what, in future research?",
      options: ["Pharmacological treatments", "Other relaxation methods", "No intervention at all", "Different types of academic curriculum"],
      correctAnswerIndex: 1,
      reference: "Page 5, Conclusion",
      difficulty: 'medium',
    },
    {
      questionText: "According to Kwong et al. (2023), chronic anxiety during adolescence is a risk factor for depression, low self-esteem, and what other issue in young adulthood?",
      options: ["Physical illness", "Financial instability", "Burnout", "Social isolation"],
      correctAnswerIndex: 2,
      reference: "Page 2, Paragraph 3",
      difficulty: 'medium',
    },
    {
      questionText: "The study by Wang et al. (2023) is cited as evidence for the Butterfly Hug reducing what specific type of anxiety?",
      options: ["Social anxiety", "Test-related anxiety", "Separation anxiety", "Generalized anxiety"],
      correctAnswerIndex: 1,
      reference: "Page 2, Paragraph 5",
      difficulty: 'medium',
    },
    {
        questionText: "The affirmation stage of the Butterfly Hug is linked to what specific positive outcome in the abstract?",
        options: ["Increased focus", "Better peer relationships", "Stronger self-acceptance and self-appreciation", "Higher HARS scores"],
        correctAnswerIndex: 2,
        reference: "Page 1, Abstract",
        difficulty: 'medium',
    },
    {
        questionText: "Qualitative data from interviews were analyzed 'thematically'. What does this process primarily involve?",
        options: ["Counting the frequency of specific words", "Identifying patterns and themes in the narrative data", "Statistically comparing interview answers", "Ranking participants based on their responses"],
        correctAnswerIndex: 1,
        reference: "Page 4, Section 3, citing Braun & Clarke (2021)",
        difficulty: 'medium',
    },
    {
        questionText: "Why is it significant that the Butterfly Hug is a 'self-administered' method?",
        options: ["It means it is less effective than therapist-led methods.", "It empowers individuals to manage their emotions independently.", "It requires expensive equipment to use.", "It can only be used once a day."],
        correctAnswerIndex: 1,
        reference: "Page 2, Paragraph 4 & Page 5, Paragraph 4",
        difficulty: 'medium',
    },
    {
        questionText: "What two factors make anxiety disorders in children different from those in adults, according to the 'Theory of Anxiety' section?",
        options: ["They are less severe and shorter in duration.", "They are the earliest to form and often linked to separation or specific phobias.", "They are untreatable and always lead to depression.", "They are only caused by academic pressure."],
        correctAnswerIndex: 1,
        reference: "Page 2, Section 2.1",
        difficulty: 'medium',
    },
    {
        questionText: "The study's findings are 'in line with' Wahdi et al. (2024), who noted what trend in Indonesia?",
        options: ["A decrease in academic performance", "A rise in cases of adolescent anxiety", "An increase in boarding school enrollment", "A decline in mental health resources"],
        correctAnswerIndex: 1,
        reference: "Page 5, Paragraph 4",
        difficulty: 'medium',
    },
    {
        questionText: "What does the paper suggest is the ultimate goal of integrating this technique into school mental health programs?",
        options: ["To eliminate all stress from students' lives", "To replace traditional academic subjects", "To support students' emotional resilience", "To monitor students' thoughts"],
        correctAnswerIndex: 2,
        reference: "Page 5, Conclusion",
        difficulty: 'medium',
    },
    {
        questionText: "The research by Pristianto et al. (2022) examined the combination of the Butterfly Hug and what other technique?",
        options: ["Mindful journaling", "Aromatherapy", "Deep breathing", "Art therapy"],
        correctAnswerIndex: 2,
        reference: "Page 3, Section 2.3",
        difficulty: 'medium',
    },
    {
        questionText: "The study's methodology aimed for a 'holistic understanding'. What does this imply?",
        options: ["Focusing only on the numerical HARS scores", "Considering only the participants' own words", "Looking at the whole picture, including emotions, behaviors, and context", "Only observing participants from a distance"],
        correctAnswerIndex: 2,
        reference: "Page 4, Section 3",
        difficulty: 'medium',
    },
    {
        questionText: "What is the key difference between 'psychic anxiety' and 'somatic anxiety' as measured by HARS?",
        options: ["There is no difference.", "Psychic is future-oriented, somatic is past-oriented.", "Psychic refers to mental/emotional symptoms, while somatic refers to physical symptoms.", "Psychic anxiety is measured by interviews, somatic by observation."],
        correctAnswerIndex: 2,
        reference: "Page 3, Section 2.2",
        difficulty: 'medium',
    },
    {
        questionText: "Why was 'purposive sampling' the appropriate choice for this study?",
        options: ["The researchers wanted a random group of students.", "The researchers needed to specifically select students who were showing signs of anxiety.", "This method is the easiest and fastest available.", "The school administration required this method."],
        correctAnswerIndex: 1,
        reference: "Page 4, Section 3",
        difficulty: 'medium',
    },
    {
        questionText: "The paper highlights an 'urgent need' to address adolescent anxiety. What is the basis for this urgency?",
        options: ["A single case reported at NFBS", "A significant increase in prevalence in recent years, both globally and in Indonesia", "A new government mandate", "The upcoming school examinations"],
        correctAnswerIndex: 1,
        reference: "Page 2, Paragraph 2",
        difficulty: 'medium',
    },
    {
        questionText: "The study's results suggest the technique enhances calmness and builds what personal quality among adolescents?",
        options: ["Competitiveness", "Self-compassion", "Skepticism", "Ambition"],
        correctAnswerIndex: 1,
        reference: "Page 5, Paragraph 4",
        difficulty: 'medium',
    },
    {
        questionText: "In the context of the Butterfly Hug, what does 'bilateral stimulation' refer to?",
        options: ["Thinking about two things at once", "Stimulating both hemispheres of the brain, typically through alternating sensory input", "Writing with both hands simultaneously", "Engaging in two different relaxation techniques at the same time"],
        correctAnswerIndex: 1,
        reference: "Page 2, Paragraph 4",
        difficulty: 'medium',
    },
    {
        questionText: "What specific finding from the interviews most strongly supports the idea that the technique helps reframe negative self-perception?",
        options: ["The feeling of being hugged by a mother", "The commitment to continue using the hug", "Sharing affirmations of self-acceptance like 'we made it through'", "The observation that participants were calmer"],
        correctAnswerIndex: 2,
        reference: "Page 5, Paragraph 3",
        difficulty: 'medium',
    },
    {
        questionText: "According to the paper, what makes anxiety disorders in children and adolescents a foundational mental health issue?",
        options: ["They are the easiest to treat", "They are the most common type and represent the earliest form of mental illness", "They do not impact adult life", "They are a new phenomenon"],
        correctAnswerIndex: 1,
        reference: "Page 2, Section 2.1",
        difficulty: 'medium',
    },
    {
        questionText: "How did the researchers ensure the study was 'descriptive in nature'?",
        options: ["By proving a cause-and-effect relationship", "By aiming to portray the participants' experiences rather than test a hypothesis", "By using complex statistical models", "By comparing the results to a control group"],
        correctAnswerIndex: 1,
        reference: "Page 4, Section 3, citing Stake (2020)",
        difficulty: 'medium',
    },
    // 25 Medium Questions from external sources
    {
      questionText: "Who is credited with developing the Butterfly Hug technique, particularly for survivors of trauma?",
      options: ["Francine Shapiro", "Lucina Artigas", "Bessel van der Kolk", "Peter A. Levine"],
      correctAnswerIndex: 1,
      reference: "https://www.emdria.org/blog/the-butterfly-hug-method/",
      difficulty: 'medium',
    },
    {
        questionText: "The Butterfly Hug is a form of Bilateral Stimulation (BLS). What is the proposed neurological theory explaining why BLS works?",
        options: ["It increases blood flow to the prefrontal cortex.", "It mimics the eye movements of REM sleep, helping the brain process memories.", "It releases a surge of adrenaline, creating a sense of alertness.", "It temporarily shuts down the amygdala's fear response."],
        correctAnswerIndex: 1,
        reference: "https://doi.org/10.3389/fnhum.2014.00735",
        difficulty: 'medium',
    },
    {
        questionText: "EMDR therapy, from which the Butterfly Hug originates, was initially and most famously developed to treat what condition?",
        options: ["Generalized Anxiety Disorder (GAD)", "Obsessive-Compulsive Disorder (OCD)", "Post-Traumatic Stress Disorder (PTSD)", "Major Depressive Disorder (MDD)"],
        correctAnswerIndex: 2,
        reference: "https://www.apa.org/ptsd-guideline/treatments/eye-movement-reprocessing",
        difficulty: 'medium',
    },
    {
        questionText: "Beyond anxiety reduction, what is another common therapeutic goal of using the Butterfly Hug in a clinical setting?",
        options: ["To create a 'safe place' or resource for grounding during distressing moments.", "To analyze the content of dreams.", "To improve physical coordination and balance.", "To enhance logical reasoning skills."],
        correctAnswerIndex: 0,
        reference: "https://www.esthervanderpol.com/self-help/butterfly-hug/",
        difficulty: 'medium',
    },
    {
        questionText: "The bilateral tapping in the Butterfly Hug is a form of 'somatic' intervention. What does 'somatic' mean in this context?",
        options: ["Relating to the mind and thoughts", "Relating to social interactions", "Relating to the body", "Relating to past experiences"],
        correctAnswerIndex: 2,
        reference: "https://www.psychologytoday.com/us/therapy-types/somatic-therapy",
        difficulty: 'medium',
    },
    {
        questionText: "What is the name of the overarching theory behind EMDR, which posits that trauma is unprocessed or maladaptively stored information?",
        options: ["Cognitive Dissonance Theory", "Attachment Theory", "Adaptive Information Processing (AIP) model", "Polyvagal Theory"],
        correctAnswerIndex: 2,
        reference: "https://www.emdr.com/what-is-emdr/",
        difficulty: 'medium',
    },
    {
        questionText: "In addition to tapping, what other forms can self-administered Bilateral Stimulation (BLS) take?",
        options: ["Holding a specific posture", "Listening to alternating tones in headphones", "Regulating body temperature", "Drinking a specific type of tea"],
        correctAnswerIndex: 1,
        reference: "https://www.choosingtherapy.com/bilateral-stimulation",
        difficulty: 'medium',
    },
    {
        questionText: "The effectiveness of the Butterfly Hug relies on engaging the 'parasympathetic nervous system'. What is the primary function of this system?",
        options: ["'Fight or Flight' response, preparing for action", "'Rest and Digest' response, promoting calmness", "Processing sensory information from the eyes", "Controlling voluntary muscle movements"],
        correctAnswerIndex: 1,
        reference: "https://my.clevelandclinic.org/health/body/23273-parasympathetic-nervous-system-psns",
        difficulty: 'medium',
    },
    {
        questionText: "What is a key difference between using the Butterfly Hug for self-soothing and undergoing full EMDR therapy?",
        options: ["There is no difference.", "The Butterfly Hug is more effective.", "Full EMDR therapy involves processing specific traumatic memories with a trained therapist.", "The Butterfly Hug can only be done in a group setting."],
        correctAnswerIndex: 2,
        reference: "https://www.forbes.com/health/mind/emdr-therapy/",
        difficulty: 'medium',
    },
    {
        questionText: "The 'grounding' effect of the Butterfly Hug helps individuals experiencing anxiety or dissociation to do what?",
        options: ["Mentally escape from their current situation.", "Reconnect with the present moment and their body.", "Analyze the root cause of their anxiety.", "Fall asleep quickly."],
        correctAnswerIndex: 1,
        reference: "https://www.healthline.com/health/grounding-techniques",
        difficulty: 'medium',
    },
    {
        questionText: "Which part of the brain, often called the 'fear center', is typically overactive in anxiety and is calmed by techniques like the Butterfly Hug?",
        options: ["Hippocampus", "Prefrontal Cortex", "Cerebellum", "Amygdala"],
        correctAnswerIndex: 3,
        reference: "https://doi.org/10.3389/fpsyg.2017.01997",
        difficulty: 'medium',
    },
    {
        questionText: "The Butterfly Hug was famously used with survivors of what natural disaster in Mexico in 1998?",
        options: ["Earthquake", "Hurricane Pauline", "Volcanic Eruption", "Tsunami"],
        correctAnswerIndex: 1,
        reference: "https://www.youtube.com/watch?v=iGGJrqscvtU (EMDRIA Channel)",
        difficulty: 'medium',
    },
    {
        questionText: "Adolescent brains are particularly sensitive to stress due to ongoing development in which brain region responsible for decision-making and impulse control?",
        options: ["Brainstem", "Occipital Lobe", "Prefrontal Cortex", "Parietal Lobe"],
        correctAnswerIndex: 2,
        reference: "https://www.nimh.nih.gov/health/publications/the-teen-brain-7-things-to-know",
        difficulty: 'medium',
    },
    {
        questionText: "Self-compassion, a quality the Butterfly Hug can foster, involves treating oneself with kindness, a sense of common humanity, and what other component?",
        options: ["Self-criticism", "Perfectionism", "Mindfulness", "Ambition"],
        correctAnswerIndex: 2,
        reference: "https://self-compassion.org/the-three-elements-of-self-compassion-2/",
        difficulty: 'medium',
    },
    {
        questionText: "What is a potential risk of using self-help techniques like the Butterfly Hug without professional guidance for severe trauma?",
        options: ["It might be ineffective.", "It could inadvertently bring up overwhelming emotions or memories.", "It is too expensive.", "It takes too long to learn."],
        correctAnswerIndex: 1,
        reference: "https://www.emdria.org/public-resources/is-emdr-therapy-right-for-me/",
        difficulty: 'medium',
    },
    {
        questionText: "From a neurobiological perspective, rhythmic, repetitive motions like tapping are known to have what effect?",
        options: ["They are inherently regulating and soothing for the nervous system.", "They increase cognitive load and stress.", "They have no effect on the brain.", "They exclusively activate the brain's language centers."],
        correctAnswerIndex: 0,
        reference: "https://doi.org/10.1177/1049732313505028",
        difficulty: 'medium',
    },
    {
        questionText: "The concept of 'Window of Tolerance' describes the optimal zone of arousal where a person can function effectively. How does the Butterfly Hug relate to this concept?",
        options: ["It pushes a person outside their window of tolerance.", "It helps a person return to their window of tolerance when they are hyper-aroused (anxious) or hypo-aroused (numb).", "It shrinks the window of tolerance over time.", "It has no relationship to the window of tolerance."],
        correctAnswerIndex: 1,
        reference: "https://www.nicabm.com/trauma-how-to-help-your-clients-understand-their-window-of-tolerance/",
        difficulty: 'medium',
    },
    {
        questionText: "For adolescents, peer relationships are a major factor in mental well-being. How might a technique that reduces social anxiety benefit this area?",
        options: ["It would make them want to avoid social situations.", "It could increase their confidence and willingness to engage socially.", "It would have no impact on their social life.", "It would make them overly dependent on their friends for validation."],
        correctAnswerIndex: 1,
        reference: "https://www.unicef.org/parenting/mental-health/adolescent-mental-health",
        difficulty: 'medium',
    },
    {
        questionText: "The 'mind-body connection' is central to somatic techniques. This idea suggests that mental and emotional states are...",
        options: ["completely separate from physical states.", "only influenced by external events.", "deeply intertwined with and can be influenced by the body's physical state.", "are determined solely by genetics."],
        correctAnswerIndex: 2,
        reference: "https://www.apa.org/monitor/2019/12/cover-mind-body",
        difficulty: 'medium',
    },
    {
        questionText: "The speed of tapping in the Butterfly Hug is generally recommended to be:",
        options: ["As fast as possible.", "Very slow and deliberate.", "A rhythm that feels comfortable and soothing to the individual.", "Synchronized with a metronome at 120 bpm."],
        correctAnswerIndex: 2,
        reference: "https://www.youtube.com/watch?v=xS5SIA7_R2U (Video by EMDR therapist)",
        difficulty: 'medium',
    },
    {
        questionText: "What is a common criticism of EMDR and its associated techniques?",
        options: ["It is too new to have any research.", "The bilateral stimulation is an unnecessary component; the effects are due to traditional exposure therapy elements.", "It only works on children.", "It is a form of hypnotism."],
        correctAnswerIndex: 1,
        reference: "https://doi.org/10.1002/14651858.CD003388.pub5",
        difficulty: 'medium',
    },
    {
        questionText: "The term 'emotional regulation', a key outcome of the Butterfly Hug, refers to a person's ability to:",
        options: ["Suppress all emotions completely.", "Exaggerate emotions for effect.", "Influence which emotions they have, when they have them, and how they experience and express them.", "Only experience positive emotions."],
        correctAnswerIndex: 2,
        reference: "https://www.apa.org/research/action/emotion",
        difficulty: 'medium',
    },
    {
        questionText: "Why might a non-verbal, body-based technique like the Butterfly Hug be particularly useful for adolescents?",
        options: ["Adolescents are incapable of talking about their feelings.", "It bypasses the need to find the 'right words' for complex emotions, which can be difficult.", "It is a more fun and engaging activity than talking.", "It is the only method schools are allowed to use."],
        correctAnswerIndex: 1,
        reference: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3621523/",
        difficulty: 'medium',
    },
    {
        questionText: "What does the 'H' in the HARS scale (Hamilton Anxiety Rating Scale) stand for?",
        options: ["Health", "Human", "Hamilton", "Holistic"],
        correctAnswerIndex: 2,
        reference: "https://www.psychiatry.org/psychiatrists/practice/dsm/educational-resources/assessment-measures (Under Anxiety)",
        difficulty: 'medium',
    },
    {
        questionText: "The use of self-soothing techniques is a core component of what major therapeutic modality that focuses on mindfulness and emotional regulation?",
        options: ["Psychoanalysis", "Dialectical Behavior Therapy (DBT)", "Humanistic Therapy", "Rational Emotive Behavior Therapy (REBT)"],
        correctAnswerIndex: 1,
        reference: "https://my.clevelandclinic.org/health/treatments/22838-dialectical-behavior-therapy-dbt",
        difficulty: 'medium',
    }
  ];

  const advance: Question[] = [
    // 5 Advance Questions from the provided paper
    {
      questionText: "Given the study's finding that participants developed 'stronger self-acceptance', how does the 'affirmation stage' of the Butterfly Hug process, as implied by the abstract, contribute to this outcome?",
      options: ["The affirmation stage is not mentioned in the study's methods.", "It requires participants to receive praise from others.", "It likely combines the physical self-soothing of tapping with positive self-talk, directly addressing negative cognitive patterns.", "It focuses solely on breathing, which calms the body but not the mind."],
      correctAnswerIndex: 2,
      reference: "Page 1, Abstract, Last sentence",
      difficulty: 'advance',
    },
    {
      questionText: "The paper proposes integrating the Butterfly Hug into school programs to support 'students' emotional resilience'. What does emotional resilience mean in a psychological context?",
      options: ["The inability to feel negative emotions.", "The process of adapting well in the face of adversity, trauma, tragedy, or significant sources of stress.", "The tendency to rely on others for emotional support.", "The skill of hiding one's true feelings from others."],
      correctAnswerIndex: 1,
      reference: "Page 5, Conclusion (Concept Application)",
      difficulty: 'advance',
    },
    {
        questionText: "The study's design is described as 'descriptive' and aiming to 'portray rather than test phenomena'. What is a primary limitation of this research design?",
        options: ["The results cannot be generalized to a wider population.", "It provides no meaningful data.", "It is more expensive than experimental designs.", "It cannot be published in academic journals."],
        correctAnswerIndex: 0,
        reference: "Page 4, Section 3 (Methodological implication)",
        difficulty: 'advance',
    },
    {
        questionText: "The paper links adolescent anxiety to later-life depression and burnout. How might an early intervention like the Butterfly Hug theoretically disrupt this trajectory?",
        options: ["It can't; the trajectory is genetically determined.", "By teaching self-regulation skills early, it equips individuals with tools to manage stress before it becomes chronic and leads to more severe conditions.", "It eliminates all academic and social pressure from a student's life.", "It only provides a temporary distraction, with no long-term impact."],
        correctAnswerIndex: 1,
        reference: "Page 2, Paragraph 3 & Page 5, Conclusion (Synthesis of concepts)",
        difficulty: 'advance',
    },
    {
        questionText: "The integration of quantitative (HARS scores) and qualitative (interview) data is a hallmark of what research approach?",
        options: ["Purely Quantitative Research", "Purely Qualitative Research", "Mixed Methods Research", "Theoretical Research"],
        correctAnswerIndex: 2,
        reference: "Page 4, Section 3 (Citing Creswell & Creswell, 2022)",
        difficulty: 'advance',
    },
    // 45 Advance Questions from external sources
    {
      questionText: "What are the 8 phases of standard EMDR therapy, of which the Butterfly Hug would be a resource used within?",
      options: ["Assessment, Engagement, Intervention, Evaluation, Termination, Follow-up, Crisis, and Planning", "History-taking, Preparation, Assessment, Desensitization, Installation, Body Scan, Closure, and Re-evaluation", "Introduction, Exploration, Understanding, Action, Consolidation, Maintenance, and Relapse Prevention", "Observation, Hypothesis, Experimentation, Conclusion, Reporting, Review, Revision, and Theory"],
      correctAnswerIndex: 1,
      reference: "https://www.emdr.com/what-is-emdr/ (Under '8 Phases of Treatment')",
      difficulty: 'advance',
    },
    {
        questionText: "According to Polyvagal Theory, the Butterfly Hug's calming effect likely activates the 'ventral vagal complex'. What state is this system associated with?",
        options: ["A state of 'freeze' or dissociation", "A 'fight or flight' response", "A state of social engagement and safety", "A state of deep sleep"],
        correctAnswerIndex: 2,
        reference: "https://doi.org/10.3389/fpsyt.2018.00049",
        difficulty: 'advance',
    },
    {
        questionText: "Neuroimaging studies of EMDR show decreased activity in the amygdala and increased activity in brain regions associated with emotional regulation and memory consolidation. Which region is primarily involved in the latter?",
        options: ["The Pons", "The Cerebellum", "The Hippocampus", "The Medulla Oblongata"],
        correctAnswerIndex: 2,
        reference: "https://doi.org/10.1016/j.euroneuro.2013.04.004",
        difficulty: 'advance',
    },
    {
        questionText: "A major debate in EMDR research is the 'active ingredient'. One critical perspective suggests its efficacy is not from BLS, but from what common factor in trauma therapies?",
        options: ["The therapeutic relationship", "The use of positive affirmations", "The element of imaginal exposure to the traumatic memory", "The specific seating arrangement in the room"],
        correctAnswerIndex: 2,
        reference: "https://doi.org/10.1177/0004867413478235",
        difficulty: 'advance',
    },
    {
        questionText: "When used for trauma, the Butterfly Hug should ideally be 'resourced' first. What does this mean in a therapeutic context?",
        options: ["The client pays for the session in advance.", "The client first learns to associate the hug with a feeling of calm and safety before using it for distressing material.", "The client is given a manual on how to perform the hug.", "The therapist demonstrates the hug on themselves first."],
        correctAnswerIndex: 1,
        reference: "https://www.goodtherapy.org/blog/psychpedia/resourcing",
        difficulty: 'advance',
    },
    {
        questionText: "In what situation might the use of a grounding technique like the Butterfly Hug be contraindicated for an individual?",
        options: ["When they are feeling mild anxiety", "When they have severe dissociative symptoms and may be destabilized without a therapist present", "When they are in a good mood", "Before taking an important exam"],
        correctAnswerIndex: 1,
        reference: "https://did-research.org/treatment/grounding",
        difficulty: 'advance',
    },
    {
        questionText: "The 'Adaptive Information Processing' (AIP) model is the theoretical basis for EMDR. What does it propose about mental health?",
        options: ["Mental health is determined by a balance of brain chemicals.", "Pathology is caused by experiences stored dysfunctionally in isolated neural networks.", "All mental illness is genetic.", "Positive thinking can cure any psychological disorder."],
        correctAnswerIndex: 1,
        reference: "https://www.emdria.org/about-emdr-therapy/the-aip-model/",
        difficulty: 'advance',
    },
    {
        questionText: "How does 'interoception'—the sense of the internal state of the body—relate to the effectiveness of the Butterfly Hug?",
        options: ["It has no relation.", "The hug enhances interoceptive awareness, helping individuals notice and regulate their physiological state of anxiety.", "The hug decreases interoceptive awareness, distracting from anxiety.", "Interoception is only related to feelings of hunger and thirst."],
        correctAnswerIndex: 1,
        reference: "https://doi.org/10.1016/j.cortex.2012.01.001",
        difficulty: 'advance',
    },
    {
        questionText: "Some research suggests that Bilateral Stimulation (BLS) works by disrupting the vividness of distressing memories held in what cognitive system?",
        options: ["Long-term memory", "Procedural memory", "Working memory", "Semantic memory"],
        correctAnswerIndex: 2,
        reference: "https://doi.org/10.1016/j.jbtep.2008.06.001",
        difficulty: 'advance',
    },
    {
        questionText: "The Butterfly Hug can be seen as a form of 'applied mindfulness'. How does it differ from traditional meditation?",
        options: ["It is less effective.", "It incorporates active, physical grounding rather than passive observation.", "It requires religious belief.", "It can only be practiced for a few seconds at a time."],
        correctAnswerIndex: 1,
        reference: "https://www.apa.org/topics/mindfulness/meditation",
        difficulty: 'advance',
    },
    {
        questionText: "Which neurotransmitter, associated with feelings of well-being and social bonding, is likely released during self-soothing behaviors like the Butterfly Hug?",
        options: ["Cortisol", "Adrenaline", "Oxytocin", "Glutamate"],
        correctAnswerIndex: 2,
        reference: "https://doi.org/10.3389/fnbeh.2013.00179",
        difficulty: 'advance',
    },
    {
        questionText: "In the context of adolescent development, Erik Erikson's psychosocial stage is 'Identity vs. Role Confusion'. How might chronic anxiety impact the resolution of this stage?",
        options: ["It has no impact.", "It can inhibit exploration and commitment, leading to role confusion.", "It accelerates the formation of a stable identity.", "It makes adolescents more confident in their choices."],
        correctAnswerIndex: 1,
        reference: "https://www.simplypsychology.org/erik-erikson.html",
        difficulty: 'advance',
    },
    {
        questionText: "What is the primary difference between 'state anxiety' and 'trait anxiety'?",
        options: ["State anxiety is a temporary condition, while trait anxiety is a stable personality characteristic.", "State anxiety is physical, while trait anxiety is mental.", "Only adults experience trait anxiety.", "They are measured using the exact same scale."],
        correctAnswerIndex: 0,
        reference: "https://www.apa.org/pubs/highlights/spotlight/issue-111",
        difficulty: 'advance',
    },
    {
        questionText: "The bilateral aspect of the Butterfly Hug is theorized to promote 'interhemispheric communication' in the brain. What does this refer to?",
        options: ["The suppression of one brain hemisphere.", "The communication between the left and right hemispheres of the brain.", "The connection between the brain and the spinal cord.", "The firing of neurons within a single hemisphere."],
        correctAnswerIndex: 1,
        reference: "https://doi.org/10.1080/10874208.2012.684381",
        difficulty: 'advance',
    },
    {
        questionText: "The HARS scale is a clinician-administered instrument. What is a key limitation of such scales compared to self-report measures?",
        options: ["They are less accurate.", "They are subject to the clinician's interpretation and potential bias.", "They take less time to complete.", "They cannot be used for research."],
        correctAnswerIndex: 1,
        reference: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6489427/",
        difficulty: 'advance',
    },
    {
        questionText: "How does the 'top-down' vs 'bottom-up' processing framework apply to techniques like the Butterfly Hug?",
        options: ["The hug is a 'top-down' technique that changes thoughts to change feelings.", "The hug is a 'bottom-up' technique that uses bodily sensations to change emotional states.", "The framework does not apply.", "The hug is both, happening simultaneously."],
        correctAnswerIndex: 1,
        reference: "https://www.nicabm.com/trauma-how-the-5-steps-of-bottom-up-processing-can-help-clients-regulate-fear/",
        difficulty: 'advance',
    },
    {
        questionText: "From a psycho-educational perspective, what is the value of teaching adolescents the 'why' behind the Butterfly Hug (i.e., its effect on the nervous system)?",
        options: ["It is too complex and will confuse them.", "It demystifies the process and increases their buy-in and sense of empowerment.", "It has no added value compared to just teaching the technique.", "It is unethical to share this information with non-clinicians."],
        correctAnswerIndex: 1,
        reference: "https://www.frontiersin.org/articles/10.3389/fpsyg.2019.02240/full",
        difficulty: 'advance',
    },
    {
        questionText: "The concept of 'allostatic load' refers to the cumulative wear and tear on the body from chronic stress. How would effective self-regulation impact this?",
        options: ["It would increase allostatic load.", "It would have no effect.", "It would help reduce the frequency of the stress response, thereby lowering allostatic load over time.", "Allostatic load is a fixed, unchangeable measure."],
        correctAnswerIndex: 2,
        reference: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1197825/",
        difficulty: 'advance',
    },
    {
        questionText: "Bessel van der Kolk's influential book, 'The Body Keeps the Score', champions what type of therapeutic approaches for trauma and anxiety?",
        options: ["Strictly talk-based therapies.", "Body-based, somatic approaches that address physiological dysregulation.", "Medication-only approaches.", "Ignoring the trauma and focusing on the future."],
        correctAnswerIndex: 1,
        reference: "https://www.besselvanderkolk.com/resources/the-body-keeps-the-score",
        difficulty: 'advance',
    },
    {
        questionText: "What is a key difference between anxiety and fear?",
        options: ["They are the same thing.", "Fear is a response to a specific, immediate threat, while anxiety is often future-oriented and diffuse.", "Anxiety is a healthy emotion, while fear is not.", "Fear is purely psychological, while anxiety is purely physical."],
        correctAnswerIndex: 1,
        reference: "https://www.apa.org/topics/anxiety/anxiety-fear",
        difficulty: 'advance',
    },
    {
        questionText: "The 'Orienting Response' is the nervous system's automatic reaction to novelty. How can this be used therapeutically with a technique like the Butterfly Hug?",
        options: ["It can't be used.", "By focusing on the novel physical sensation of tapping, it can interrupt a ruminative anxiety cycle.", "The orienting response always increases anxiety.", "It is only relevant for visual stimuli."],
        correctAnswerIndex: 1,
        reference: "https://www.psychologytools.com/resource/orienting/",
        difficulty: 'advance',
    },
    {
        questionText: "What is 'co-regulation', and how does the Butterfly Hug mimic it?",
        options: ["Co-regulation is regulating emotions with another person; the hug internalizes this by providing a self-soothing, nurturing gesture.", "Co-regulation is a legal term in therapy.", "Co-regulation involves taking medication and doing therapy.", "It doesn't mimic it."],
        correctAnswerIndex: 0,
        reference: "https://www.frontiersin.org/articles/10.3389/fpsyg.2021.733519/full",
        difficulty: 'advance',
    },
    {
        questionText: "In Acceptance and Commitment Therapy (ACT), 'cognitive defusion' is the process of separating from one's thoughts. How could the Butterfly Hug aid in this process?",
        options: ["By reinforcing the literal truth of anxious thoughts.", "By shifting focus to bodily sensations, it creates distance from thoughts, allowing them to be observed rather than believed.", "By analyzing the origin of each thought.", "By replacing anxious thoughts with mandatory positive ones."],
        correctAnswerIndex: 1,
        reference: "https://www.actmindfully.com.au/about-act/",
        difficulty: 'advance',
    },
    {
        questionText: "What does the term 'neuroception' coined by Stephen Porges refer to?",
        options: ["The conscious perception of risk.", "The brain's ability to learn new languages.", "The nervous system's ability to distinguish safe, dangerous, and life-threatening situations without conscious awareness.", "The process of neurogenesis."],
        correctAnswerIndex: 2,
        reference: "https://www.stephenporges.com/neuroception",
        difficulty: 'advance',
    },
    {
        questionText: "The efficacy of Bilateral Stimulation is sometimes attributed to 'taxing working memory'. Why would this be helpful for anxiety?",
        options: ["It makes the person too tired to feel anxious.", "It reduces the capacity of working memory available to hold onto vivid, distressing images or thoughts.", "It improves working memory, allowing for better problem-solving.", "It has no effect on working memory."],
        correctAnswerIndex: 1,
        reference: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2905133/",
        difficulty: 'advance',
    },
    {
        questionText: "Which ethical principle is most relevant when considering the use of self-help techniques from a clinical therapy with vulnerable populations like adolescents?",
        options: ["Beneficence (acting in the best interest of the client)", "Do No Harm (avoiding exploitation or harm)", "Confidentiality (protecting client information)", "All of the above"],
        correctAnswerIndex: 1,
        reference: "https://www.apa.org/ethics/code",
        difficulty: 'advance',
    },
    {
        questionText: "What is 'titration' in the context of trauma therapy, and how does the Butterfly Hug facilitate it?",
        options: ["It's a chemical process.", "It means exposing the client to overwhelming trauma all at once.", "It means touching on distressing material in small, manageable doses, with the hug used as a tool to regulate between exposures.", "It refers to the duration of the therapy session."],
        correctAnswerIndex: 2,
        reference: "https://www.goodtherapy.org/blog/psychpedia/titration",
        difficulty: 'advance',
    },
    {
        questionText: "The concept of 'neuroplasticity' is fundamental to therapeutic change. What does it mean?",
        options: ["The brain is rigid and unchangeable after childhood.", "The brain's ability to reorganize itself by forming new neural connections throughout life.", "The material that the brain is made of.", "A surgical procedure to improve brain function."],
        correctAnswerIndex: 1,
        reference: "https://www.psychologytoday.com/us/basics/neuroplasticity",
        difficulty: 'advance',
    },
    {
        questionText: "Some EMDR protocols use 'Dual Attention Stimulus'. What does this refer to?",
        options: ["The client paying attention to two therapists at once.", "The client focusing on both an internal memory and an external bilateral stimulus (like tapping) simultaneously.", "The therapist paying attention to both the client's words and body language.", "Watching a screen with two different images."],
        correctAnswerIndex: 1,
        reference: "https://www.emdrconsulting.com/what-is-dual-attention-stimulus/",
        difficulty: 'advance',
    },
    {
        questionText: "How does the 'fight, flight, freeze' model of threat response relate to the symptoms of anxiety described in the paper?",
        options: ["It doesn't relate.", "Symptoms like agitation (fight/flight) and withdrawal (freeze/shutdown) are direct manifestations of these nervous system states.", "The model only applies to animals, not humans.", "The model describes healthy coping mechanisms."],
        correctAnswerIndex: 1,
        reference: "https://www.health.harvard.edu/staying-healthy/understanding-the-stress-response",
        difficulty: 'advance',
    },
    {
        questionText: "What is a 'meta-analysis' in research, and why would it be important for validating a technique like the Butterfly Hug?",
        options: ["A single, small case study.", "A study that analyzes a single individual's metabolism.", "A statistical analysis that combines the results of multiple scientific studies, providing a high level of evidence.", "A non-scientific review of existing literature."],
        correctAnswerIndex: 2,
        reference: "https://www.cochrane.org/glossary/meta-analysis",
        difficulty: 'advance',
    },
    {
        questionText: "How might 'epigenetic' factors (changes in gene expression without changing DNA sequence) be relevant to adolescent anxiety?",
        options: ["They are not relevant.", "Chronic stress during the crucial developmental period of adolescence can cause epigenetic changes that increase long-term vulnerability to mental illness.", "Epigenetics only relates to physical traits like hair color.", "Good grades can positively change your genes."],
        correctAnswerIndex: 1,
        reference: "https://www.cdc.gov/genomics/disease/epigenetics.htm",
        difficulty: 'advance',
    },
    {
        questionText: "Why is the rhythm of bilateral stimulation important? (e.g., crossing the midline of the body)",
        options: ["It's not important; any tapping works.", "Crossing the midline is thought to engage both brain hemispheres more effectively.", "It makes the technique harder to learn, and therefore more powerful.", "It's a tradition with no scientific basis."],
        correctAnswerIndex: 1,
        reference: "https://www.ahealth.com/content/education/developmental/crossing-the-midline",
        difficulty: 'advance',
    },
    {
        questionText: "What is a 'confounding variable' that could have influenced the results of the case study in the paper?",
        options: ["The Butterfly Hug itself", "The extra attention and support the participants received from the researchers", "The HARS scale's scoring", "The time of day the intervention was performed"],
        correctAnswerIndex: 1,
        reference: "https://www.simplypsychology.org/confounding-variables.html",
        difficulty: 'advance',
    },
    {
        questionText: "The 'Social Baseline Theory' suggests the human brain expects access to social relationships. How does this relate to anxiety in a boarding school setting?",
        options: ["It suggests humans are better off alone.", "The separation from primary attachment figures (family) violates this baseline, creating a state of threat and anxiety.", "It only applies to adults in the workplace.", "It states that online friendships are a perfect substitute for in-person ones."],
        correctAnswerIndex: 1,
        reference: "https://doi.org/10.3389/fnins.2016.00257",
        difficulty: 'advance',
    },
    {
        questionText: "In attachment theory, the Butterfly Hug could be seen as a way to provide 'internal secure attachment'. What does this mean?",
        options: ["Locking the doors to feel secure.", "Developing an internal sense of safety and self-worth, independent of external validation.", "Becoming emotionally detached from others.", "The ability to form many friendships quickly."],
        correctAnswerIndex: 1,
        reference: "https://www.psychologytoday.com/us/blog/compassion-matters/201307/how-create-secure-attachment-in-yourself",
        difficulty: 'advance',
    },
    {
        questionText: "How does 'rumination'—the tendency to repetitively think about negative feelings and problems—contribute to anxiety?",
        options: ["It helps to solve the problem.", "It keeps the individual in a state of heightened alert and emotional distress, amplifying anxiety.", "It is a form of mindfulness.", "It has no effect on anxiety levels."],
        correctAnswerIndex: 1,
        reference: "https://www.apa.org/ptsd-guideline/patients-and-families/cognitive-behavioral",
        difficulty: 'advance',
    },
    {
        questionText: "What is the role of the 'Vagus Nerve' in the mind-body connection, and how might the Butterfly Hug influence it?",
        options: ["It has no role.", "The Vagus Nerve is the main nerve of the parasympathetic system; rhythmic breathing and soothing touch can stimulate it, promoting a relaxation response.", "The Vagus Nerve controls voluntary movement only.", "The Vagus Nerve is only located in the brain."],
        correctAnswerIndex: 1,
        reference: "https://my.clevelandclinic.org/health/body/22279-vagus-nerve",
        difficulty: 'advance',
    },
    {
        questionText: "How does a 'placebo effect' differ from a genuine therapeutic effect, and why is it a concern in studies without a control group?",
        options: ["A placebo effect is stronger.", "A placebo effect is when improvement results from the belief in a treatment, not the treatment itself. Without a control group, it's hard to separate the two.", "A placebo is a form of medication.", "There is no difference."],
        correctAnswerIndex: 1,
        reference: "https://www.health.harvard.edu/mental-health/the-power-of-the-placebo-effect",
        difficulty: 'advance',
    },
    {
        questionText: "What is 'affect tolerance' and how would practicing the Butterfly Hug improve it?",
        options: ["The complete avoidance of negative feelings.", "The ability to experience uncomfortable emotions without becoming overwhelmed; the hug provides a tool to stay grounded during these feelings.", "A personality trait that cannot be changed.", "The capacity to feel empathy for others."],
        correctAnswerIndex: 1,
        reference: "https://www.psychologytoday.com/us/blog/childhood-emerging/202101/affect-tolerance",
        difficulty: 'advance',
    },
    {
        questionText: "Why might research on somatic techniques be more challenging to standardize and measure than research on pharmacological interventions?",
        options: ["It is not more challenging.", "Individual experiences of bodily sensation are subjective, and technique application can vary, unlike a standardized pill dosage.", "There is no funding for somatic research.", "Somatic techniques are too new to have established measures."],
        correctAnswerIndex: 1,
        reference: "https://www.frontiersin.org/articles/10.3389/fnhum.2021.579383/full",
        difficulty: 'advance',
    },
    {
        questionText: "The practice of 'containment' in therapy involves creating a sense of safety for intense emotions. How can the Butterfly Hug be used as a personal containment skill?",
        options: ["By suppressing emotions until they disappear.", "The physical act of hugging oneself provides a symbolic and physiological container, helping to manage overwhelming feelings.", "By sharing the feelings with as many people as possible.", "Containment is not a therapeutic concept."],
        correctAnswerIndex: 1,
        reference: "https://www.goodtherapy.org/blog/psychpedia/containment",
        difficulty: 'advance',
    },
    {
        questionText: "What is the primary function of the 'Default Mode Network' (DMN) in the brain, and how is it related to anxiety?",
        options: ["It controls motor functions.", "It is active during focused tasks.", "It is active during rest and self-referential thought; overactivity is linked to rumination and anxiety.", "It processes visual information."],
        correctAnswerIndex: 2,
        reference: "https://www.psychologytoday.com/us/basics/default-mode-network",
        difficulty: 'advance',
    },
    {
        questionText: "Sleep disruption is a common symptom of anxiety. How might a self-soothing technique practiced before bed impact sleep quality?",
        options: ["It would likely worsen sleep by increasing alertness.", "By calming the nervous system and reducing anxious thoughts, it could make it easier to fall asleep and improve sleep quality.", "It would have no impact on sleep.", "It can replace the need for sleep entirely."],
        correctAnswerIndex: 1,
        reference: "https://www.sleepfoundation.org/mental-health/anxiety-and-sleep",
        difficulty: 'advance',
    },
    {
        questionText: "What is 'vicarious trauma' or 'secondary traumatic stress', and who is at risk?",
        options: ["Trauma experienced directly.", "Stress from watching a traumatic film.", "Stress resulting from helping or wanting to help a traumatized or suffering person; therapists, first responders, and even peers are at risk.", "A type of physical injury."],
        correctAnswerIndex: 2,
        reference: "https://www.apa.org/topics/stress/vicarious-trauma",
        difficulty: 'advance',
    },
    {
        questionText: "How does the 'dual-awareness' cultivated in techniques like the Butterfly Hug (awareness of the present tapping and the past/internal feeling) help in processing difficult emotions?",
        options: ["It is confusing and unhelpful.", "It anchors the person in the present safety while allowing them to touch on distressing material, preventing them from being completely overwhelmed.", "It forces the person to relive the trauma fully.", "Dual-awareness is not a goal of the technique."],
        correctAnswerIndex: 1,
        reference: "https://www.emdr-europe.org/uploads/2020-EMDR-and-dissociation-the-progressive-approach.pdf",
        difficulty: 'advance',
    },
    {
        questionText: "What distinguishes a 'case study' from an 'experimental study' in terms of research goals?",
        options: ["Case studies aim for in-depth understanding of a specific case, while experiments aim to establish cause-and-effect relationships.", "Case studies use more participants.", "Experiments are less scientific.", "There is no difference in their goals."],
        correctAnswerIndex: 0,
        reference: "https://www.simplypsychology.org/case-study.html",
        difficulty: 'advance',
    },
  ];
  
  return {
      easy,
      medium,
      advance,
  };
};

export const QUIZ_DATA = generateQuestions();
